[general]
OPENAI_API_KEY = "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"
ADMIN_PASSWORD = "admin123"